Board/Board/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('pages/', include('django.contrib.flatpages.urls')),
                  path('posts/', include('posts.urls')),
                  path('accounts/', include('allauth.urls')),
                  path('logout/', auth_views.LogoutView.as_view(), name='logout'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Board/posts/urls.py
from django.urls import path

from .views import ArticleList, ArticleDetail, ArticleCreate, ArticleUpdate, ArticleDelete, CommentCreate
from .views import AuthorArticleList, CommentDelete, CommentStatusUpdate

urlpatterns = [
   path('', ArticleList.as_view(), name='post_list'),
   path('<int:pk>', ArticleDetail.as_view(), name='post'),
   path('create/', ArticleCreate.as_view(), name='post_add'),
   path('<int:pk>/update/', ArticleUpdate.as_view(), name='post_update'),
   path('<int:pk>/delete/', ArticleDelete.as_view(), name='post_delete'),
   path('<int:pk>/add/', CommentCreate.as_view(), name='comment_add'),
   path('author_articles/', AuthorArticleList.as_view(), name='author_articles'),
   path('comment/<int:pk>/delete/', CommentDelete.as_view(), name='comment_delete'),
   path('comment/<int:pk>/status/', CommentStatusUpdate.as_view(), name='comment_status_update'),


]

Board/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Article(models.Model):
    TYPE = (
        ('tank', 'Танки'),
        ('heal', 'Хилы'),
        ('dd', 'ДД'),
        ('buyers', 'Торговцы'),
        ('gildemaster', 'Гилдмастеры'),
        ('quest', 'Квестгиверы'),
        ('smith', 'Кузнецы'),
        ('tanner', 'Кожевники'),
        ('potion', 'Зельевары'),
        ('spellmaster', 'Мастера заклинаний'),
    )
    authorPost = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=64)
    text = models.TextField()
    category = models.CharField(max_length=11, choices=TYPE, default=None)
    dateArticle = models.DateTimeField(auto_now_add=True)
    upload = models.FileField(upload_to='uploads/')

    def __str__(self):
        return f'{self.title.title()}: {self.text[:20]}'

    def get_absolute_url(self):
        return reverse('post', args=[str(self.id)])


class UserResponse(models.Model):
    authorComment = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateComment = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.text[:20]}'

    def get_absolute_url(self):
        return reverse('post', args=[str(self.id)])

    def update_status(self, status):
        self.status = status
        self.save()

Board/accounts/forms.py
from allauth.account.forms import SignupForm
from django.contrib.auth.models import Group


class CustomSignupForm(SignupForm):
    def save(self, request):
        user = super().save(request)
        authors = Group.objects.get(name="authors")
        user.groups.add(authors)
        return user

Board/posts/forms.py
from django import forms

from django.core.exceptions import ValidationError

from .models import Article, UserResponse


class ArticleForm(forms.ModelForm):
    user = None

    class Meta:
        model = Article
        fields = ['title', 'text', 'category', 'upload']

    def clean(self):
        cleaned_data = super().clean()
        text = cleaned_data.get("text")
        title = cleaned_data.get("title")

        if title == text:
            raise ValidationError(
                "Содержание не должно быть идентично заголовку."
            )

        return cleaned_data

    def save(self, commit=True, **kwargs):
        article = super().save(commit=False, **kwargs)
        article.authorPost = self.user
        if commit:
            article.save()
        return article


class CommentForm(forms.ModelForm):
    class Meta:
        model = UserResponse
        fields = ['text']
        widgets = {'article': forms.HiddenInput(), 'status': forms.HiddenInput()}

    def save(self, commit=True, **kwargs):
        comment = super().save(commit=False, **kwargs)
        comment.authorComment = self.user
        if commit:
            comment.save()
        return comment

Board/posts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Article, UserResponse

from .forms import ArticleForm, CommentForm

from .filters import ArticleFilter


class ArticleList(ListView):
    model = Article
    ordering = '-dateArticle'
    template_name = 'posts.html'
    context_object_name = 'posts'
    paginate_by = 5


class AuthorArticleList(LoginRequiredMixin, ListView):
    model = Article
    ordering = '-dateArticle'
    context_object_name = 'articles'
    template_name = 'author_articles.html'
    paginate_by = 5

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(authorPost=self.request.user)
        self.filterset = ArticleFilter(self.request.GET, queryset)

        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['filterset'] = self.filterset
        return context


class ArticleDetail(DetailView):
    model = Article
    template_name = 'post.html'
    context_object_name = 'post'


class ArticleCreate(LoginRequiredMixin, CreateView):
    form_class = ArticleForm
    model = Article
    template_name = 'post_add.html'

    def form_valid(self, form):
        form.user = self.request.user  # передаем текущего пользователя в форму
        return super().form_valid(form)


class ArticleUpdate(UpdateView):
    form_class = ArticleForm
    model = Article
    template_name = 'post_add.html'

    def form_valid(self, form):
        form.user = self.request.user
        return super().form_valid(form)


class ArticleDelete(DeleteView):
    model = Article
    template_name = 'post_delete.html'
    success_url = reverse_lazy('post_list')


class CommentCreate(CreateView):
    form_class = CommentForm
    model = UserResponse
    template_name = 'comment_add.html'

    def form_valid(self, form):
        form.user = self.request.user
        # Получаем объект комментария, которые заполнил пользователь
        response = form.save(commit=False)
        # Находим объект объявления, которому был оставлен комментарий
        article = Article.objects.get(pk=self.kwargs['pk'])
        # Сохраняем этот объект и устанавливаем соответствующее значение поля
        # article с помощью созданного ранее скрытого поля
        response.article = article
        response.save()
        form.save_m2m()
        # Делаем редирект к странице, на которой был оставлен комментарий
        return redirect(article.get_absolute_url())


class CommentDelete(DeleteView):
    model = UserResponse
    template_name = 'comment_delete.html'
    success_url = reverse_lazy('author_articles')


class CommentStatusUpdate(LoginRequiredMixin, UpdateView):
    model = UserResponse
    fields = ['status']
    template_name = 'update_status.html'

    def form_valid(self, form):
        form.instance.update_status(form.cleaned_data['status'])
        return redirect('author_articles')

Board/templates/author_articles.html
{% extends 'flatpages/default.html' %}


{% block title %}
Post
{% endblock title %}

{% block content %}
{% load static %}
<h1>Объявления автора</h1>
<hr>
   <form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" class="mt-3 btn-primary" value="Найти" />
   </form>

    <hr>
  <style>
   .btn0 {
    display: inline-block;
    background: #008080;
    color: #000;
    padding: 0.2rem 0.5rem;
    text-decoration: none;
    border-radius: 10px;
   }
  </style>

  <style>
   .btn1 {
    display: inline-block;
    background: #B8860B;
    color: #000;
    padding: 0.2rem 0.5rem;
    text-decoration: none;
    border-radius: 10px;
   }
  </style>
  <style>
   .btn2 {
    display: inline-block;
    background: #FF0000;
    color: #000;
    padding: 0.2rem 0.5rem;
    text-decoration: none;
    border-radius: 10px;
   }
  </style>

<style>
  table {
    margin: 0 auto; /* задаем отступы, чтобы таблица была по центру */
    text-align: center; /* задаем выравнивание содержимого ячеек таблицы по центру */
  }
</style>
{% for article in articles %}
<li class="list-group-item">
    <a>{{article.title}}</a>
    <small class="text-muted">(автор: {{article.authorPost}})</small>
    <small class="text-muted">(Дата публикации:{{article.dateArticle|date:' M d Y'}})</small><br>
    <small class="fw-bold">Персонаж: {{article.get_category_display}}</small>
    <p>{{article.text}}</p>
    <div>
        <img src="{{ article.upload.url}}"width="300" height="250">
            <p></p>
            <div>
                <a href="{% url 'post_update' pk=article.id %}" class="btn1">Редактировать</a>
            </div>
    </div>

</li>
<p></p>
   {% if article.userresponse_set.all %}
        <table>
            <tr>
                <td><b>Автор</b></td>
                <td><b>Комментарий</b></td>
                <td><b>Дата публикации</b></td>
                <td><b>Действия</b></td>

            </tr>
 <p>Комментарии к объявлению:</p>
        {% for comment in article.userresponse_set.all %}
            <tr>
                <td>{{comment.authorComment}}</td>
                <td>{{comment.text}}</td>
                <td>{{comment.dateComment|date:'M d Y'}}</td>
                <td>
                    {% if comment.status %}
                        <a href="{% url 'comment_status_update' pk=comment.id %}" class="btn2">Отменить</a>

                    {% else %}
                        <a href="{% url 'comment_status_update' pk=comment.id %}" class="btn0">Принять</a>
                        <a href="{% url 'comment_delete' comment.id %}" class="btn2">Удалить</a>
                    {% endif %}
                </td>

            </tr>
        {% endfor %}
        </table>
   {% else %}
    <!-- Если постов нет, говорим, что постов нет ;) -->
        <p>К данному объявлению еще не было оставлено комментариев</p>
   {% endif %}
<hr>
    {% endfor %}

   {# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
{% endblock content %}

Board/templates/comment_add.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Новый комментарий</h1>
<hr>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

Board/templates/comment_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление комментария</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.text }}"?</p>
    <input type="submit" value="Удалить" />
</form>
{% endblock content %}

Board/templates/post.html
{% extends 'flatpages/default.html' %}


{% block title %}
Post
{% endblock title %}

{% block content %}
  <style>
   .btn0 {
    display: inline-block;
    background: #008080;
    color: #000;
    padding: 0.2rem 0.5rem;
    text-decoration: none;
    border-radius: 10px;
   }
  </style>

  <style>
   .btn1 {
    display: inline-block;
    background: #B8860B;
    color: #000;
    padding: 0.2rem 0.5rem;
    text-decoration: none;
    border-radius: 10px;
   }
  </style>
  <style>
   .btn2 {
    display: inline-block;
    background: #FF0000;
    color: #000;
    padding: 0.2rem 0.5rem;
    text-decoration: none;
    border-radius: 10px;
   }
  </style>
<style>
  table {
    margin: 0 auto; /* задаем отступы, чтобы таблица была по центру */
    text-align: center; /* задаем выравнивание содержимого ячеек таблицы по центру */
  }
</style>
<li class="list-group-item">
    <a>{{post.title}}</a>
    <small class="text-muted">(автор: {{post.authorPost}})</small>
    <small class="text-muted">(Дата публикации:{{post.dateArticle|date:' M d Y'}})</small><br>
    <small class="fw-bold">Персонаж: {{post.get_category_display}}</small>
    <p>{{post.text}}</p>
    <img src="{{ post.upload.url}}"width="300" height="250">
</li>
<p></p>
   {% if post.userresponse_set.all %}
        <table>
            <tr>
                <td><b>Автор</b></td>
                <td><b>Комментарий</b></td>
                <td><b>Дата публикации</b></td>
            </tr>
 <p>Комментарии к объявлению:</p>
        {% for comment in post.userresponse_set.all %}
          {% if comment.status %}
            <tr>
                <td>{{comment.authorComment}}</td>
                <td>{{comment.text}}</td>
                <td>{{comment.dateComment|date:'M d Y'}}</td>
            </tr>
          {% endif %}
        {% endfor %}
        </table>
   {% else %}
        <p>К данному объявлению еще не было оставлено комментариев</p>
   {% endif %}

{% endblock content %}

Board/templates/post_add.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Новое объявление</h1>
<hr>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% if post %}
  <h3>Succesfully uploaded : {{post.title}}</h3>
  <img src="{{ post.upload.url}}" alt="connect" style="max-height:300px">
{% endif %}
{% endblock content %}

Board/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление объявления</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}"?</p>
    <input type="submit" value="Удалить" />
</form>
{% endblock content %}

Board/templates/posts.html
{% extends 'flatpages/default.html' %}

{% block title %}

Posts
{% endblock title %}


{% block content %}
{% load static %}
  <style>
   .btn0 {
    display: inline-block;
    background: #008080;
    color: #000;
    padding: 0.2rem 0.5rem;
    text-decoration: none;
    border-radius: 10px;
   }
  </style>

  <style>
   .btn1 {
    display: inline-block;
    background: #B8860B;
    color: #000;
    padding: 0.2rem 0.5rem;
    text-decoration: none;
    border-radius: 10px;
   }
  </style>
  <style>
   .btn2 {
    display: inline-block;
    background: #FF0000;
    color: #000;
    padding: 0.2rem 0.5rem;
    text-decoration: none;
    border-radius: 10px;
   }
  </style>

    {% if posts %}
        <ul class="list-group list-group-flush">
            {% for post in posts %}
                <li class="list-group-item">
                    <a href="{% url 'post' post.id %}">{{post.title}}</a>
                    <small class="text-muted">(Автор: {{post.authorPost}})</small>
                    <small class="text-muted">(Дата публикации:{{post.dateArticle|date:' M d Y'}})</small> <br>
                    <small class="fw-bold">Персонаж: {{ post.get_category_display }}</a></small>
                    <p>{{post.text}}</p>
                    <div>
                        <img src="{{ post.upload.url}}"width="300" height="250">
                        <p></p>

                    <div>
                    {% if user.is_authenticated %}
                        <a href="{% url 'comment_add' pk=post.id %}" class="btn0">Комментировать</a>
                    {% endif %}
                        {% if perms.posts.delete_post %}
                        <a href="{% url 'post_delete' pk=post.id %}" class="btn2">Удалить</a>
                        {% endif %}
                    </div>
                    </div>

                </li>
            {% endfor %}
        </ul>
    {% else %}

        <h2>Постов нет!</h2>
    {% endif %}


   {# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
{% endblock content %}

Board/templates/profile.html
<!DOCTYPE html>
<html>
<head>
    <title>Profile</title>
</head>
<body>
    <h2>Profile</h2>
    <p>Welcome, {{ user.username }}!</p>
    <p>Your email address is: {{ user.email }}</p>
</body>
</html>

Board/templates/update_status.html
{% extends 'flatpages/default.html' %}

{% block title %}Обновляем комментарий{% endblock title %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Update</button>
  </form>
{% endblock content %}